#!/bin/bash
set -e
gitdir=$(git rev-parse --git-dir)
rm -f "$gitdir"/CHERRY_PICK_HEAD.bak
mv "$gitdir"/CHERRY_PICK_HEAD{,.bak} 2>/dev/null || true
git date-truncate --tips
mv "$gitdir"/CHERRY_PICK_HEAD{.bak,} 2>/dev/null || true
